const database = require('../database');

/* PlatformUser Entity
Represents a user registered on the platform */

/**
 * @property {string} id
 *   Unique identifier for the user.
 *   - Auto-generated by the database (e.g., SERIAL or UUID)
 *   - Use Default when creating a new user
 */

/**
 * @property {string} name
 *   Full name of the user.
 *   - Domain: PersonNames (letters and spaces only, max 100 characters)
 *   - Example: "Mathew"
 */

/**
 * @property {string} email
 *   Email address of the user.
 *   - Domain: EmailAddress (must be unique, valid email format)
 *   - Example: "name@example.com"
 */

/**
 * @property {string} password_hash
 *   password string.supposed to be hashed but now just a string.
 */

/**
 * @property {string} role
 *   Role of the user in the system.
 *   - Example values: "student", "tutor", "admin"
 */

/**
 * @property {Date} registered_at
 *   Timestamp of user registration.
 *   - Auto-generated by the database using CURRENT_TIMESTAMP
 *   - use default when creating a new user
 */
const createPlatformUser = async (name, email, password_hash, role) => {
    return database.any(
        `INSERT INTO platformuser 
            (id, name, email, password_hash, role, registered_at)
         VALUES 
            (DEFAULT, $1, $2, $3, $4, DEFAULT)
         RETURNING id`,
        [name, email, password_hash, role]
    );
}

module.exports = {
    createPlatformUser,
}