const database = require('../database');

/* This file is about the PlatformUser Entity
Represents a user registered on the platform */

/**
 * @property {string} id
 *   Unique identifier for the user.
 *   - Auto-generated by the database (e.g., SERIAL or UUID)
 *   - Use Default when creating a new user
 * @property {string} name
 *   Full name of the user.
 *   - consists of upper or lowercase letters, or spaces. 
 *   - It won't allow numbers, punctuation, or special characters
 *   - Domain: PersonNames (letters and spaces only, max 100 characters)
 *   - Example: "Mathew"

 * @property {string} email
 *   Email address of the user.
 *   - Domain: EmailAddress (must be unique, valid email format)
 *   - Example: "name@example.com"
 * @property {string} password_hash
 *   password string.supposed to be hashed but now just a string.
 * @property {string} role
 *   Role of the user in the system.
 *   - Example values: "student", "tutor", "admin"
 * @property {Date} registered_at
 *   Timestamp of user registration.
 *   - Auto-generated by the database using CURRENT_TIMESTAMP
 *   - use default when creating a new user
 * @return {string} id
 *   Unique identifier for the newly created user.
 *   - Example: "123e4567-e89b-12d3-a456-426614174000"
 */
const createPlatformUser = async (name, email, password_hash, role) => {
    // for debugging purpose
    // console.log("createPlatformUser called");
    // console.log("name:", name);
    // console.log("name type:", typeof name);
    // console.log("name length:", name?.length);
    // console.log("name JSON:", JSON.stringify(name));
    // console.log("name char codes:", name ? [...name].map(c => c.charCodeAt(0)) : 'undefined');
    // console.log("email:", email);
    // console.log("password_hash:", password_hash);
    // console.log("role:", role);
    const result = await database.one(
        `INSERT INTO platformuser 
            (id, name, email, password_hash, role, registered_at)
         VALUES 
            (DEFAULT, $1, $2, $3, $4, DEFAULT)
         RETURNING id`,
        [name, email, password_hash, role]
    );
    return result.id;
}

/** 
 * retrieve the password associated with the user’s email
 * */ 
const getPasswordByEmail = async (email) => {
    // for debugging purpose
    console.log("getPasswordByEmail called");
    console.log("email:", email);
    console.log("email type:", typeof email);
    const result = await database.one(
        `SELECT password_hash FROM platformuser WHERE email = $1`,
        [email]
    );
    return result.password_hash;
}

/**
 * retrive the user by email
 * @param {string} email - The email of the user to retrieve.
 * @returns {Promise<Object>} - The user object containing id, name, email, password_hash, role, and registered_at.
 */
const getUserByEmail = async (email) => {
    try {
        console.log("Searching for user with email:", email);
        
        // Add a query to check if any users exist at all
        const userCount = await database.one('SELECT COUNT(*) as count FROM platformuser');
        console.log("Total users in database:", userCount.count);
        
        // Check if the specific email exists (case-insensitive)
        const emailCheck = await database.oneOrNone(
            'SELECT email FROM platformuser WHERE LOWER(email) = LOWER($1)',
            [email]
        );
        console.log("Email found (case-insensitive):", emailCheck);
        
        const result = await database.one(
            `SELECT id as platform_user_id, name, email, password_hash, role, registered_at 
             FROM platformuser 
             WHERE email = $1`,
            [email]
        );
        return result;
    } catch (error) {
        console.log("Database error:", error.message);
        if (error.message === 'No data returned from the query.') {
            return null;
        }
        throw error;
    }
}

module.exports = {
    createPlatformUser,
    getPasswordByEmail,
    getUserByEmail
}