const studentRepository = require('../repositories/studentRepository');
const platformUserRepository = require('../repositories/platformUserRepository');
const hasStudentProfileInRepository = require('../repositories/hasStudentProfileInRepository');

const getAllStudents = async () => {
  return await studentRepository.queryAllStudents();
};


/**
 * add a new student. First, create a student in the database,
 * then create a platform user for the student, and use the returned student_code and id to create a HasStudentProfileIn
 * @property {string} name
 *   Full name of the user.
 *   - Domain: PersonNames (letters and spaces only, max 100 characters)
 *   - Example: "Mathew"
 * @property {string} email
 *   Email address of the user.
 *   - Domain: EmailAddress (must be unique, valid email format)
 *   - Example: "name@example.com"
 * @property {string} password
 *   password string.supposed to be hashed but now just a string.
 * @property {string} role
 *   Role of the user in the system.
 *   - Example values: "student", "tutor", "admin"
 * @returns {string} student_code
 *   Unique code for the student, generated by the system.
 *   - Example: "STU123456"
 */
// todo:if have time the password_hash should be hashed using bcrypt or similar library
const registerStudent = async ({name, email, password, role}) => {
  const password_hash = password;
  const student_code = await studentRepository.createStudent();
  // console.log("createStudent successful");
  // console.log("student_code", student_code);
  const platform_user_id = await platformUserRepository.createPlatformUser(name, email, password_hash, role);
  // console.log("platformUser is created");
  // console.log("platform_user_id", platform_user_id);
  await hasStudentProfileInRepository.createHasStudentProfileIn(student_code, platform_user_id);
  // console.log("HasStudentProfileIn is created");
  // console.log("student_code", student_code);
  // console.log("About to return student_code");
  return student_code;
};

/**
 * verfy if the student role user login by comparing the email and password
 * and return the student_code and platform_user_id if the login is successful
 */
const verifyStudentLogin = async (email, password) => {
  // assuming password will be hashed in the future
  const password_hash = await platformUserRepository.getPasswordByEmail(email);
  if (password_hash === password) {
    const platform_user = await platformUserRepository.getUserByEmail(email);
    const platform_user_id = platform_user.id;
    const student_code = await hasStudentProfileInRepository.getStudentCodeByPlatformUserId(platform_user_id);
    return {student_code, platform_user_id};
  } else {
    throw new Error('Invalid email or password');
  }
}

module.exports = {
  getAllStudents,
  registerStudent,
  verifyStudentLogin
};