-- Drop Join Tables
DROP TABLE IF EXISTS LabelCourseWith CASCADE;
DROP TABLE IF EXISTS LabelContentWith CASCADE;
DROP TABLE IF EXISTS OwnCourseBy CASCADE;
DROP TABLE IF EXISTS LogCourseProgressAt CASCADE;
DROP TABLE IF EXISTS LogContentProgressAt CASCADE;
DROP TABLE IF EXISTS HasCourseProgressFor CASCADE;
DROP TABLE IF EXISTS HasContentProgressFor CASCADE;
DROP TABLE IF EXISTS InterestedIn CASCADE;
DROP TABLE IF EXISTS HasTopicReferenceTo CASCADE;
DROP TABLE IF EXISTS HasStudentProfileIn CASCADE;
DROP TABLE IF EXISTS HasLearningModeFor CASCADE;
DROP TABLE IF EXISTS HasCourseReferenceTo CASCADE;
DROP TABLE IF EXISTS EnrolsIn CASCADE;
DROP TABLE IF EXISTS Comprises CASCADE;

-- Drop Main Tables
DROP TABLE IF EXISTS ChosenTopic CASCADE;
DROP TABLE IF EXISTS CourseProgress CASCADE;
DROP TABLE IF EXISTS CopyrightOwner CASCADE;
DROP TABLE IF EXISTS CourseContent CASCADE;
DROP TABLE IF EXISTS Enrolment CASCADE;
DROP TABLE IF EXISTS Course CASCADE;
DROP TABLE IF EXISTS LearningMode CASCADE;
DROP TABLE IF EXISTS Topic CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;